### ISSUE TITLE
swagger-ui.html link is broken

### ISSUE THREAD

**Issue by kburger** [FAIRDataTeam/fairmetadata4j#19]
https://github.com/FAIRDataTeam/fairmetadata4j/blob/9bb743adad66284da44cd21a71a98189f16e1639/src/main/java/nl/dtl/fairmetadata4j/utils/MetadataUtils.java#L345

The link created as `metadata.getUri().toString() + "/swagger-ui.html"`, which results in a link relative to the fdp root, e.g. `http://localhost:8080/fdp/swagger-ui.html`. The actual path is not a child of the fdp root, but a sibling, e.g. `http://localhost:8080/swagger-ui.html`.

**Comment by rajaram5** [comment]
We will move this logic to the FairDataPoint project. The default fdp metdata is created in the FairDataPoint application so it makes sense to move this logic.
